AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SubnetID:
    Type: String
    ServiceName:
      Type: String
    ServiceVersion:
      Type: String
    DockerHubUsername:
      Type: String
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: deployement-example-cluster
    ServiceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: ServiceSecurityGroup
        GroupDescription: Security Group for Service
        SecurityGroupIngress:
          -IpProtocol: tcp
            FromPort: 8080
            ToPort: 8080
            CidrIp: 0.0.0.0/0
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ServiceName}-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: !Sub ${ServiceName}-container
          Image: !Sub ${DockerHubUsername}/${ServiceName}:${ServiceVersion}
          PostMappings:
            - ContainerPort: 8080
      RequiresCompatibilities:
        - EC2
        - FARGATE
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${ServiceName}-service
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefiniton
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicId: ENABLED
          Subnets:
            - !Ref SubnetId
          SecurityGroups:
            - !GetAtt ServiceSecurityGroup.Group




